# Copyright (C) 2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/asus/zc520tl/setup-makefiles.sh

LOCAL_PATH := vendor/asus/zc520tl

include $(LOCAL_PATH)/zc520tl-vendor-bin.mk
include $(LOCAL_PATH)/zc520tl-vendor-firmware.mk


PRODUCT_COPY_FILES += \
    $(LOCAL_PATH)/proprietary/vendor/lib/libbluetoothem_mtk.so:system/vendor/lib/libbluetoothem_mtk.so         	  \
    $(LOCAL_PATH)/proprietary/vendor/lib/libbluetooth_mtk_pure.so:system/vendor/lib/libbluetooth_mtk_pure.so   	  \
    $(LOCAL_PATH)/proprietary/vendor/lib/libbluetooth_mtk.so:system/vendor/lib/libbluetooth_mtk.so 	     	  \
    $(LOCAL_PATH)/proprietary/vendor/lib/libcvsd_mtk.so:system/vendor/lib/libcvsd_mtk.so 		 	     	  \
    $(LOCAL_PATH)/proprietary/vendor/lib/libion_mtk.so:system/vendor/lib/libion_mtk.so 			     	  \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmtkcam_sysutils.so:system/vendor/lib/libmtkcam_sysutils.so         	  \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmtkcam_stdutils.so:system/vendor/lib/libmtkcam_stdutils.so         	  \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmtkcam_metadata.so:system/vendor/lib/libmtkcam_metadata.so         	  \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmtkcam_imgbuf.so:system/vendor/lib/libmtkcam_imgbuf.so             	  \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmtkcam_grallocutils.so:system/vendor/lib/libmtkcam_grallocutils.so 	  \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmtkcam_fwkutils.so:system/vendor/lib/libmtkcam_fwkutils.so         	  \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmtkcam_device3.so:system/vendor/lib/libmtkcam_device3.so           	  \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmtkcam_device3_app.so:system/vendor/lib/libmtkcam_device3_app.so   	  \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmtkcam_device1.so:system/vendor/lib/libmtkcam_device1.so           	  \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmtkcam_debugutils.so:system/vendor/lib/libmtkcam_debugutils.so     	  \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmtk_drvb.so:system/vendor/lib/libmtk_drvb.so                       	  \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmtkjpeg.so:system/vendor/lib/libmtkjpeg.so                         	  \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmtklimiter_vendor.so:system/vendor/lib/libmtklimiter_vendor.so     	  \
    $(LOCAL_PATH)/proprietary/vendor/lib/libmtkshifter_vendor.so:system/vendor/lib/libmtkshifter_vendor.so     	  \
    $(LOCAL_PATH)/proprietary/vendor/lib/libMtkOmxVorbisEnc.so:system/vendor/lib/libMtkOmxVorbisEnc.so         	  \
    $(LOCAL_PATH)/proprietary/vendor/lib/libMtkOmxVenc.so:system/vendor/lib/libMtkOmxVenc.so                   	  \
    $(LOCAL_PATH)/proprietary/vendor/lib/libMtkOmxVdecEx.so:system/vendor/lib/libMtkOmxVdecEx.so               	  \
    $(LOCAL_PATH)/proprietary/vendor/lib/libMtkOmxRawDec.so:system/vendor/lib/libMtkOmxRawDec.so               	  \
    $(LOCAL_PATH)/proprietary/vendor/lib/libMtkOmxMp3Dec.so:system/vendor/lib/libMtkOmxMp3Dec.so               	  \
    $(LOCAL_PATH)/proprietary/vendor/lib/libMtkOmxGsmDec.so:system/vendor/lib/libMtkOmxGsmDec.so               	  \
    $(LOCAL_PATH)/proprietary/vendor/lib/libMtkOmxG711Dec.so:system/vendor/lib/libMtkOmxG711Dec.so             	  \
    $(LOCAL_PATH)/proprietary/vendor/lib/libMtkOmxCore.so:system/vendor/lib/libMtkOmxCore.so                   	  \
    $(LOCAL_PATH)/proprietary/vendor/lib/libMtkOmxApeDec.so:system/vendor/lib/libMtkOmxApeDec.so               	  \
    $(LOCAL_PATH)/proprietary/vendor/lib/libMtkOmxAdpcmEnc.so:system/vendor/lib/libMtkOmxAdpcmEnc.so                \
    $(LOCAL_PATH)/proprietary/vendor/lib/libMtkOmxAdpcmDec.so:system/vendor/lib/libMtkOmxAdpcmDec.so           	  \
    $(LOCAL_PATH)/proprietary/vendor/lib/libreference-ril.so:system/vendor/lib/libreference-ril.so                  \
    $(LOCAL_PATH)/proprietary/vendor/lib/librilmtk.so:system/vendor/lib/librilmtk.so                                \
    $(LOCAL_PATH)/proprietary/vendor/lib/librilproxy.so:system/vendor/lib/librilproxy.so                            \
    $(LOCAL_PATH)/proprietary/vendor/lib/librilutilsmtk.so:system/vendor/lib/librilutilsmtk.so                      \
